### ISSUE TITLE
[Quickbag] `bag` alias intergration

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [countpauper/countpauper#8]
Heya, Quickbag looks neat! But maybe it'd be a good idea to add compatibility with the `bag` alias too?

**Comment by countpauper** [comment]
@Mythical-Forest-Collective quick bag is compatible with `bag` in the sense that they both use the same inventory storage. An item added with `!qb sword` should be visible when checking your `!bag`. 

If I misunderstood your suggestion, then can you give me an example in what way these aliases are not compatible?

**Comment by zombJules** [comment]
I noticed it doesn't take from the !coins alias when you place a bet.

**Comment by countpauper** [comment]
> I noticed it doesn't take from the !coins alias when you place a bet.

Hi, I think to you in discord as well? There seemed to be several issues.
1) `!coins bet` and `!coins collect`  are not yet compatible with `!g coins`, but this was not your problem
2) players were unaware that they had to `!play collect` and were betting for free and adding their winnings manually based on the embed. The footer could explains this. 
3) typoes in the coin type are easy to make (especiall g instead of gp) and are not detected as such, but as betting a custom item named "g".

1 & 3 are added to my todo list.

**Comment by countpauper** [comment]
pretty sure 1 & 3 were fixed.
